name: Docker Image CI
on:    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CR_PAT: ${{ secrets.CR_PAT }}
      IMAGE_URL: ghcr.io/aydinfurkan/game-service:${{ github.run_number }}
      CI_REGISTRY: ghcr.io
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-2
    steps:
      - uses: actions/checkout@v2
      
      - name: docker login
        run: |
          echo $CR_PAT | docker login $CI_REGISTRY -u ${{ github.run_id }} --password-stdin
          
      - name: docker build
        run: |
          docker build . --tag $IMAGE_URL
          
      - name: docker push
        run: |
          docker push $IMAGE_URL
          
  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      
      - name: Deploy in EC2
        env:
            RSA_PRIVATE_KEY: ${{ secrets.AWS_RSA_PRIVATE_KEY  }}
            ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID  }}

        run: |
          echo "$RSA_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $ACCESS_KEY_ID '

            #Now we have got the access of EC2 and we will start the deploy .
            mkdir asd
          '
      
